[package]
name = "cross-magic"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
rand = "0.9.1"
reqwest = { version = "0.12.22", features = [ "blocking" ] }
serde = { version = "1.0.219", features = [ "derive" ] }
serde_json = "1.0.140"
toml = "0.9.5"
